### ISSUE TITLE
Privately publish addon on AMO

### ISSUE THREAD

**Issue by jaredhirsch** [mozilla/universal-search-addon#73]
We will probably just let Idea Town manage installation of the privately-published AMO addon.

**Comment by pdehaan** [comment]
We could potentially leverage something like [**gulp-s3-upload**](https://www.npmjs.com/package/gulp-s3-upload) as a devDep and create some `gulp deploy` task. If I understand correctly, we'd just need an `~/.aws/credentials` file with our AWS creds, and then we just auto-deploy /dist/*\* into The Cloud.

I already have an ~/.aws/credentials file locally (not sure if it was because I have the AWS CLI installed or Boto, or something):

``` yml
✗ cat ~/.aws/credentials

[default]
aws_access_key_id = {{ access key stuff }}
aws_secret_access_key = {{ top secret stuff }}
region = us-east-1
```

**Comment by jaredhirsch** [comment]
@pdehaan yeah, I have that file too; I think the aws-sdk uses it. We should be able to get a highly restricted IAM role that can do this for us. Might also make sense to put those keys on a magic release box, so that managing them is easier than asking all the devs to update their keys. idk.

**Comment by jaredhirsch** [comment]
Actually, I'm going to close this bug. The underlying issue is that we need to coordinate with the AMO folks to get the signed, preliminarily reviewed addons to the state where they're downloadable from AMO, but not visible in search.

The addon is already preliminarily reviewed and signed, so the only issue here is coordinating with that team. Closing this bug accordingly.
