### ISSUE TITLE
Popup closes when there are no more autocomplete results

### ISSUE THREAD

**Issue by nchapman** [mozilla/universal-search-addon#77]
It seems that the popup closes when there are no autocomplete results. It should stay open as long as there are any results to choose from (search suggestions).

**Comment by jaredhirsch** [comment]
I _think_ we can fix this by checking the number of suggestions inside the `popuphiding` event handler, and canceling the event if we want to keep it open.

It's also possible that the unified autocomplete changes included a single controller that manages search and autocomplete results, in which case we can dramatically simplify how we obtain data from Gecko.

**Comment by jaredhirsch** [comment]
Looking at the unified complete behavior in nightly, it appears that typing random long gibberish strings no longer causes the popup to hide itself. Instead, the popup is filled with search suggestions.

Figure out how this works, and use it. My guess is that the new popup behavior is some new XBL popup "class" that "inherits" from the old autocomplete popup (our code does, too). We should "extend" the new popup instead.

**Comment by jaredhirsch** [comment]
It turns out that this bug is fixed as of Firefox 43, the first edition in which the unified complete stuff is landing, because the first autocomplete result is always a search suggestion for whatever the user typed.

Unfortunately, 43 will be released on 12/15, a week _after_ we're in Orlando.

So, I guess I still need to fix it ;-)
